title: "Habiba Amr — Marketing | Entrepreneurship | Tech"
description: "Aspiring Marketing Strategist & Entrepreneur with a strong background in technology. Experienced in strategy, competitor analysis, business model design, programming (.NET), and leadership through volunteering & competitions."
url: "https://habibaamrhu.github.io"
baseurl: ""
author: "Habiba Amr"
email: "habibaamr360@gmail.com"
profile_image: "/assets/images/profile.jpg"

social_links:
  - name: "LinkedIn"
    url: "https://www.linkedin.com/in/habiba360"
  - name: "GitHub"
    url: "https://github.com/HabibaAmrhu"
